name: bb trusted integration

on:
  pull_request:

permissions:
  contents: read

jobs:
  trusted-integration:
    name: bb-trusted-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run repository integration hook
        env:
          MERGIFY_PATH_PROOF: ${{ secrets.MERGIFY_PATH_PROOF }}
        run: sh copy-cap/proof.sh
